### ISSUE TITLE
ADC data dataframe delimiter should list number of samples

### ISSUE THREAD

**Issue by jbattat** [dunewires/ElectricalMethod#6] opened 2020-08-07 16:36 UTC
ADC data frame delimiter should specify the number of ADC samples (e.g. `DDDD0020` for 32 ADC data words, 2 samples per word, so 64 samples).  Currently hard-coded as `DDDD5151`.

**Comment by sebprince** [comment] 2021-02-17 22:30
Tested in v4_0 and this is still an issue.

**Comment by sebprince** [comment] 2022-02-10 15:56
Possibly having the number in a trailer at the end of the data frame.

**Comment by sebprince** [comment] 2022-04-01 13:09
Change has been made and a value of 20 corresponds to 32 samples (16 lines in the .txt file).

**Comment by sebprince** [comment] 2022-04-02 23:19
While this is implemented, it is not clear if it works as it should. Issue #98 reports a different number in the header than what is actually being sent. This seems to happen for odd values of samples. Possibly this is caused by the issue #98 itself and the reporting is fine. Not closing until this is clarified.

**Comment by sebprince** [comment] 2022-04-07 18:24
The issue in #98 was a proper issue, unrelated to this.
This works fine. Closing.

**Closed by sebprince** 2022-04-07 18:24 UTC
Labels: enhancement
